In [1]:
import pandas as pd
import numpy as np
import matplotlib
import sys
print(sys.executable)
print(matplotlib.__version__)

c:\Users\farho\anaconda3\envs\recommender_env\python.exe
3.10.3

In [2]:
import sys
!{sys.executable} -m pip show matplotlib

Name: matplotlib
Version: 3.10.3
Summary: Python plotting package
Home-page: https://matplotlib.org
Author: John D. Hunter, Michael Droettboom
Author-email: Unknown <matplotlib-users@python.org>
License: License agreement for matplotlib versions 1.3.0 and later
 =========================================================

 1. This LICENSE AGREEMENT is between the Matplotlib Development Team
 ("MDT"), and the Individual or Organization ("Licensee") accessing and
 otherwise using matplotlib software in source or binary form and its
 associated documentation.

 2. Subject to the terms and conditions of this License Agreement, MDT
 hereby grants Licensee a nonexclusive, royalty-free, world-wide license
 to reproduce, analyze, test, perform and/or display publicly, prepare
 derivative works, distribute, and otherwise use matplotlib
 alone or in any derivative version, provided, however, that MDT's
 License Agreement and MDT's notice of copyright, i.e., "Copyright (c)
 2012- Matplotlib Development Team; All Rights Reserved" are retained in
 matplotlib  alone or in any derivative version prepared by
 Licensee.

 3. In the event Licensee prepares a derivative work that is based on or
 incorporates matplotlib or any part thereof, and wants to
 make the derivative work available to others as provided herein, then
 Licensee hereby agrees to include in any such work a brief summary of
 the changes made to matplotlib .

 4. MDT is making matplotlib available to Licensee on an "AS
 IS" basis.  MDT MAKES NO REPRESENTATIONS OR WARRANTIES, EXPRESS OR
 IMPLIED.  BY WAY OF EXAMPLE, BUT NOT LIMITATION, MDT MAKES NO AND
 DISCLAIMS ANY REPRESENTATION OR WARRANTY OF MERCHANTABILITY OR FITNESS
 FOR ANY PARTICULAR PURPOSE OR THAT THE USE OF MATPLOTLIB
 WILL NOT INFRINGE ANY THIRD PARTY RIGHTS.

 5. MDT SHALL NOT BE LIABLE TO LICENSEE OR ANY OTHER USERS OF MATPLOTLIB
  FOR ANY INCIDENTAL, SPECIAL, OR CONSEQUENTIAL DAMAGES OR
 LOSS AS A RESULT OF MODIFYING, DISTRIBUTING, OR OTHERWISE USING
 MATPLOTLIB , OR ANY DERIVATIVE THEREOF, EVEN IF ADVISED OF
 THE POSSIBILITY THEREOF.

 6. This License Agreement will automatically terminate upon a material
 breach of its terms and conditions.

 7. Nothing in this License Agreement shall be deemed to create any
 relationship of agency, partnership, or joint venture between MDT and
 Licensee.  This License Agreement does not grant permission to use MDT
 trademarks or trade name in a trademark sense to endorse or promote
 products or services of Licensee, or any third party.

 8. By copying, installing or otherwise using matplotlib ,
 Licensee agrees to be bound by the terms and conditions of this License
 Agreement.

 License agreement for matplotlib versions prior to 1.3.0
 ========================================================

 1. This LICENSE AGREEMENT is between John D. Hunter ("JDH"), and the
 Individual or Organization ("Licensee") accessing and otherwise using
 matplotlib software in source or binary form and its associated
 documentation.

 2. Subject to the terms and conditions of this License Agreement, JDH
 hereby grants Licensee a nonexclusive, royalty-free, world-wide license
 to reproduce, analyze, test, perform and/or display publicly, prepare
 derivative works, distribute, and otherwise use matplotlib
 alone or in any derivative version, provided, however, that JDH's
 License Agreement and JDH's notice of copyright, i.e., "Copyright (c)
 2002-2011 John D. Hunter; All Rights Reserved" are retained in
 matplotlib  alone or in any derivative version prepared by
 Licensee.

 3. In the event Licensee prepares a derivative work that is based on or
 incorporates matplotlib  or any part thereof, and wants to
 make the derivative work available to others as provided herein, then
 Licensee hereby agrees to include in any such work a brief summary of
 the changes made to matplotlib.

 4. JDH is making matplotlib  available to Licensee on an "AS
 IS" basis.  JDH MAKES NO REPRESENTATIONS OR WARRANTIES, EXPRESS OR
 IMPLIED.  BY WAY OF EXAMPLE, BUT NOT LIMITATION, JDH MAKES NO AND
 DISCLAIMS ANY REPRESENTATION OR WARRANTY OF MERCHANTABILITY OR FITNESS
 FOR ANY PARTICULAR PURPOSE OR THAT THE USE OF MATPLOTLIB
 WILL NOT INFRINGE ANY THIRD PARTY RIGHTS.

 5. JDH SHALL NOT BE LIABLE TO LICENSEE OR ANY OTHER USERS OF MATPLOTLIB
  FOR ANY INCIDENTAL, SPECIAL, OR CONSEQUENTIAL DAMAGES OR
 LOSS AS A RESULT OF MODIFYING, DISTRIBUTING, OR OTHERWISE USING
 MATPLOTLIB , OR ANY DERIVATIVE THEREOF, EVEN IF ADVISED OF
 THE POSSIBILITY THEREOF.

 6. This License Agreement will automatically terminate upon a material
 breach of its terms and conditions.

 7. Nothing in this License Agreement shall be deemed to create any
 relationship of agency, partnership, or joint venture between JDH and
 Licensee.  This License Agreement does not grant permission to use JDH
 trademarks or trade name in a trademark sense to endorse or promote
 products or services of Licensee, or any third party.

 8. By copying, installing or otherwise using matplotlib,
 Licensee agrees to be bound by the terms and conditions of this License
 Agreement.
Location: c:\Users\farho\anaconda3\envs\recommender_env\Lib\site-packages
Requires: contourpy, cycler, fonttools, kiwisolver, numpy, packaging, pillow, pyparsing, python-dateutil
Required-by:

In [3]:
np.random.seed(123)

In [4]:

item_ratings = np.random.randint(1, 5, size=(10, 10)).astype(float)

In [5]:
missing_ratings = np.random.rand(10, 10) < 0.3
item_ratings[missing_ratings] = np.nan

In [6]:
user_ids = [f"User_{i + 1}" for i in range(10)]
item_ids = [f"Item_{x + 1}" for x in range(10)]

In [7]:
toy_df = pd.DataFrame(
    item_ratings, 
    index=user_ids, 
    columns=item_ids
    )

In [8]:
print(toy_df)

         Item_1  Item_2  Item_3  Item_4  Item_5  Item_6  Item_7  Item_8  \
User_1      NaN     2.0     3.0     3.0     1.0     3.0     3.0     2.0
User_2      4.0     2.0     3.0     2.0     1.0     NaN     3.0     NaN
User_3      NaN     1.0     4.0     2.0     NaN     3.0     2.0     NaN
User_4      1.0     2.0     4.0     4.0     3.0     1.0     4.0     NaN
User_5      1.0     2.0     1.0     4.0     2.0     4.0     NaN     1.0
User_6      2.0     2.0     NaN     NaN     4.0     3.0     2.0     1.0
User_7      3.0     2.0     NaN     4.0     3.0     3.0     3.0     3.0
User_8      1.0     NaN     NaN     4.0     2.0     1.0     NaN     1.0
User_9      4.0     NaN     1.0     3.0     3.0     NaN     1.0     NaN
User_10     NaN     NaN     4.0     3.0     2.0     4.0     2.0     NaN

         Item_9  Item_10
User_1      4.0      3.0
User_2      NaN      1.0
User_3      NaN      1.0
User_4      1.0      4.0
User_5      NaN      3.0
User_6      1.0      4.0
User_7      NaN      3.0
User_8      3.0      2.0
User_9      4.0      3.0
User_10     1.0      1.0

In [9]:
toy_df.style\
    .set_caption("Toy Ratings Matrix (10 Users × 10 Items)")\
    .format(precision=2, na_rep="NaN")